#|=======================================|
#|Bot Made By R3ido101  V Snap-0.0.1     |
#|=======================================|


# Put Your Bot Name Here.
name : !!str name

# Put your OAUTH key that you can get from https://www.twitchapps.com/tmi here.
oauth : !!str oauth:############################

# Put The Channel Here you want the bot to join.
channel : !!str channel

# If you want to give credit to friend

R3 : !!str Thank you for using the bot made by R3ido101 and friends we have a github that you can edit my code

# need to fix more shit xD LOL xD xD xD xD xD xD xD xD
